workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

stages:
  - build

build:
  stage: build
  tags:
    - docker  
  variables:
    IMAGE_NAME: "my-app" 
    DOCKER_IMAGE: "$CI_REGISTRY_IMAGE/$IMAGE_NAME:latest"
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - docker build -t "$DOCKER_IMAGE" .
    - docker push "$DOCKER_IMAGE"