services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./client.ini:/app/client.ini 
      - ./.streamlit/secrets.toml:/app/.streamlit/secrets.toml
      - ./.streamlit/config.toml:/app/.streamlit/config.toml
