import streamlit as st


def set_language():
    #settiamo la lingua di default in italiano, se non è già presente nella sessione
    if 'language' not in st.session_state:
        st.session_state['language'] = 'IT' 
    current_lang = translations[st.session_state['language']]
    return current_lang

# andiamo a definire le traduzioni in un dizionario, in modo tale da poterle usare in base alla lingua selezionata
translations = {
    "IT": {
        "login_prompt": "Effettua il login per continuare",
        "login_button": "Log in",
        "analysis_history": "Cronologia Analisi",
        "analysis_info": "Informazioni sui prodotti",
        "file_already_analyzed": "Il file {file_name} è già stato analizzato e verrà saltato.",
        "first_title": ":blue-background[Benvenuto nel nostro potente :blue[Azure AI] Data Extractor!]",
        "second_title": "Analizza i tuoi documenti e lascia che il nostro AI faccia il resto 🚀",
        "third_title": "In seguito potrai modificare i dati estratti, visualizzare il file caricato con i campi evidenziati e scaricare il file in formato JSON. ⬇️",
        "info_textinput": "Informazioni sul Venditore",
        "delete_uploaded": "Elimina i file caricati",
        "clear_warning": "Sei sicuro di voler cancellare tutta la cronologia? Questa azione non può essere annullata.",
        "clear_history": "🗑️ Pulisci Cronologia",
        "confirm_clear_history": "Sì, Pulisci Cronologia",
        "cancel_clear_history": "Annulla",
        "clear_success": "Cronologia cancellata con successo.",
        "view_analysis": "Apri Analisi",
        "analysis_details": "Dettagli Analisi",
        "close_analysis": "Chiudi",
        "history_info" : "Non è disponibile alcuna analisi in cronologia.",
        "logout_button": "Log out",
        "greeting": "Ciao, **{name}**, {email}",
        "upload_label": "Carica una Fattura o una Ricevuta",
        "success_upload": "File {file_name} caricato con successo",
        "analysis_success": "Analisi completata con successo per il file: ",
        "extract_image": "Immagine con bounding box",
        "error_upload": "Errore durante l'analisi del documento: {error}",
        "json_success": "Dati aggiornati e file JSON scaricato con successo!",
        "json_error": "Errore durante l'aggiornamento dei dati e il download: {error}",
        "text_input": ["Nome Venditore","Indirizzo Venditore","Numero di telefono Venditore","Data","Orario","PIVA","Totale"],
        "dataframe_columns": ["Descrizione", "Codice Prodotto", "Quantità", "PrezzoUnità", "Totale"],
        "update_download_button": "Aggiorna e Scarica Dati",
        "analyze_selected": "Analisi selezionata:",
        "no_file_warning": "Non è stato caricato alcun file, seguire le istruzioni corrette",
        "unsupported_file_error": "Tipo di file non supportato caricato: {file_name}",
        "invalid_file_error": "File {file_type} non valido caricato: {file_name}",
        "data_extraction_error": "Impossibile estrarre i dati dal documento.",
        "temp_path" : "Il percorso temporaneo del file non è definito.",
        "analyzing_document": "Analizzando il documento...",
        "ocr_error": "Errore durante l'OCR e la generazione del PDF: {error}",
        "rectangle_error": "Errore durante il disegno dei rettangoli: {error}",
        "data_not_found": "I dati del file per questa analisi sono mancanti."
    },
    "EN": {
        "login_prompt": "Please log in to continue",
        "login_button": "Log in",
        "analysis_history": "Analysis History",
        "analysis_info": "Product Information",
        "file_already_analyzed": "File {file_name} has already been analyzed and will be skipped.",
        "first_title": ":blue-background[Welcome to our powerful :blue[Azure AI] Data Extractor!]",
        "second_title": "Analyze your documents and let our AI do the rest 🚀",
        "third_title": "Then you can edit the extracted data, view the uploaded file with highlighted fields, and download the file in JSON format. ⬇️",
        "info_textinput": "Vendor Information",
        "delete_uploaded": "Delete Uploaded Files",
        "clear_warning": "Are you sure you want to clear all history? This action cannot be undone.",
        "clear_history": "🗑️ Clear All History",
        "confirm_clear_history": "Yes, Clear History",
        "cancel_clear_history": "Cancel",
        "clear_success": "History cleared successfully.",
        "view_analysis": "Open Analysis",
        "analysis_details": "Analysis Details",
        "close_analysis": "Close",
        "logout_button": "Log out",
        "greeting": "Hello, **{name}**, {email}",
        "upload_label": "Upload an Invoice or a Receipt",
        "success_upload": "File {file_name} uploaded successfully",
        "analysis_success": "Analysis completed successfully for file: ",
        "extract_image": "Image with bounding box",
        "error_upload": "Error during document analysis: {error}",
        "json_success": "Data updated and JSON file downloaded successfully!",
        "json_error": "Error during the data update and download: {error}",
        "text_input": ["Vendor Name", "Vendor Address", "Vendor Phone Number", "Date", "Time", "VAT Number", "Total"],
        "dataframe_columns": ["Description", "Product Code", "Quantity", "Unit Price", "Total"],
        "update_download_button": "Update and Download Data",
        "analyze_selected": "Analyze selected:",
        "no_file_warning": "There's no file uploaded, please follow the right instructions",
        "unsupported_file_error": "Unsupported file type uploaded: {file_name}",
        "invalid_file_error": "Invalid {file_type} file uploaded: {file_name}",
        "data_extraction_error": "Failed to extract data from the document.",
        "temp_path" : "The temporary file path is not defined.",
        "analyzing_document": "Analyzing the document...",
        "ocr_error": "Error during OCR and PDF generation: {error}",
        "rectangle_error": "Error during rectangle drawing: {error}",
        "data_not_found": "File data for this analysis is missing."
    },
    "ES": {
        "login_prompt": "Inicia sesión para continuar",
        "login_button": "Iniciar sesión",
        "analysis_history": "Historial de análisis",
        "analysis_info": "Información sobre los productos",
        "file_already_analyzed": "El archivo {file_name} ya ha sido analizado y se saltará.",
        "first_title": ":blue-background[Bienvenido a nuestro potente :blue[Azure AI] Data Extractor!]",
        "second_title": "Analiza tus documentos y deja que nuestra IA haga el resto 🚀",
        "third_title": "Luego podrás editar los datos extraídos, ver el archivo cargado con los campos resaltados y descargar el archivo en formato JSON.⬇️",
        "info_textinput": "Informaciòn del Vendedor",
        "delete_uploaded": "Eliminar archivos cargados",
        "clear_warning": "¿Estás seguro de que deseas limpiar todo el historial? Esta acción no se puede deshacer.",
        "clear_history": "🗑️ Limpiar todo el historial",
        "confirm_clear_history": "Sí, limpiar historial",
        "cancel_clear_history": "Cancelar",
        "clear_success": "Historial limpiado con éxito.",
        "view_analysis": "Abrir análisis",
        "analysis_details": "Detalles del análisis",
        "close_analysis": "Cerrar",
        "history_info" : "No hay análisis disponibles en el historial.",
        "logout_button": "Cerrar sesión",
        "greeting": "Hola, **{name}**, {email}",
        "upload_label": "Cargar una factura o un recibo",
        "success_upload": "Archivo {file_name} cargado con éxito",
        "analysis_success": "Análisis completado con éxito para el archivo: ",
        "extract_image": "Imagen con bounding box",
        "error_upload": "Error al analizar el documento: {error}",
        "json_success": "Datos actualizados y archivo JSON descargado con éxito!",
        "json_error": "Error al actualizar los datos y descargar: {error}",
        "text_input": ["Nombre del vendedor", "Dirección del vendedor", "Número de teléfono del vendedor", "Fecha", "Hora", "Número de IVA", "Total"],
        "dataframe_columns": ["Descripción", "Código de producto", "Cantidad", "Precio unitario", "Total"],
        "update_download_button": "Actualizar y descargar datos",
        "analyze_selected": "Análisis seleccionado:",
        "no_file_warning": "No se ha cargado ningún archivo, siga las instrucciones correctas",
        "unsupported_file_error": "Tipo de archivo no compatible cargado: {file_name}",
        "invalid_file_error": "Archivo {file_type} no válido cargado: {file_name}",
        "data_extraction_error": "No se pudieron extraer datos del documento.",
        "temp_path" : "La ruta del archivo temporal no está definida.",
        "analyzing_document": "Analizando el documento...",
        "ocr_error": "Error durante el OCR y la generación del PDF: {error}",
        "rectangle_error": "Error al dibujar los rectángulos: {error}",
        "data_not_found": "Los datos del archivo para este análisis faltan."

    }
}